ortholog_mapping_file: 'homo_sapiens_mus_musculus.txt' 
ontology_file: 'uberon.obo'

exp1: 
    id: 'E-MTAB-8410'
    species: 'homo_sapiens'
exp2: 
    id: 'E-ENAD-15'
    species: 'mus_musculus'

cell_type_field: 'inferred_cell_type_-_ontology_labels'

compare_experiments:
    min_overlap: [ 0.05, 0.1, 0.2 ]
    pval_limit: [ 1, 0.1, 0.05, 0.01, 0.001 ]
    n_genes: [ 10, 100, 1000 ]
