ortholog_mapping_file: 'homo_sapiens_mus_musculus.txt' 
ontology_file: 'uberon.obo'

exp1: 
    id: 'E-GEOD-125970'
    species: 'homo_sapiens'
exp2: 
    id: 'E-ENAD-15'
    species: 'mus_musculus'

cell_type_field: 'inferred_cell_type_-_ontology_labels'

compare_experiments:
    min_overlap: 0.1
    pval_limit: 0.05
